<?php
namespace RamirezRentACar\Database;

class Schema {
	public static function get_tables() {
		global $wpdb;
		$prefix = $wpdb->prefix . 'rrc_';
		$charset_collate = $wpdb->get_charset_collate();

		return [
			'rrc_vehicle_models' => "CREATE TABLE `{$prefix}vehicle_models` (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				post_id bigint(20) unsigned DEFAULT NULL,
				internal_code varchar(50) NOT NULL,
				public_name varchar(255) NOT NULL,
				category varchar(100) NOT NULL,
				year int(4) DEFAULT NULL,
				make varchar(100) DEFAULT NULL,
				model varchar(100) DEFAULT NULL,
				trim varchar(100) DEFAULT NULL,
				passenger_capacity int(3) DEFAULT NULL,
				luggage_capacity int(3) DEFAULT NULL,
				doors int(2) DEFAULT NULL,
				transmission varchar(50) DEFAULT NULL,
				fuel_type varchar(50) DEFAULT NULL,
				drive_type varchar(50) DEFAULT NULL,
				air_conditioning tinyint(1) DEFAULT 1,
				minimum_driver_age int(3) DEFAULT NULL,
				security_deposit_amount decimal(10,2) DEFAULT NULL,
				status varchar(50) DEFAULT 'publish',
				featured tinyint(1) DEFAULT 0,
				sort_order int(11) DEFAULT 0,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				deleted_at datetime DEFAULT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY internal_code (internal_code)
			) $charset_collate;",

			'rrc_vehicle_units' => "CREATE TABLE `{$prefix}vehicle_units` (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				vehicle_model_id bigint(20) unsigned NOT NULL,
				unit_code varchar(50) NOT NULL,
				license_plate varchar(50) NOT NULL,
				vin_encrypted text DEFAULT NULL,
				color varchar(100) DEFAULT NULL,
				current_mileage int(11) DEFAULT 0,
				location_id bigint(20) unsigned DEFAULT NULL,
				status varchar(50) DEFAULT 'available',
				service_status varchar(50) DEFAULT 'available',
				registration_expiry date DEFAULT NULL,
				insurance_expiry date DEFAULT NULL,
				last_service_at datetime DEFAULT NULL,
				next_service_at datetime DEFAULT NULL,
				notes text DEFAULT NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				deleted_at datetime DEFAULT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY unit_code (unit_code)
			) $charset_collate;",

			'rrc_vehicle_media' => "CREATE TABLE `{$prefix}vehicle_media` (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				vehicle_model_id bigint(20) unsigned NOT NULL,
				vehicle_unit_id bigint(20) unsigned DEFAULT NULL,
				attachment_id bigint(20) unsigned NOT NULL,
				media_type varchar(50) DEFAULT 'image',
				is_cover tinyint(1) DEFAULT 0,
				sort_order int(11) DEFAULT 0,
				ai_alt_text text DEFAULT NULL,
				ai_tags_json text DEFAULT NULL,
				approved_by bigint(20) unsigned DEFAULT NULL,
				approved_at datetime DEFAULT NULL,
				created_at datetime NOT NULL,
				PRIMARY KEY  (id)
			) $charset_collate;",

			'rrc_locations' => "CREATE TABLE `{$prefix}locations` (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				name varchar(255) NOT NULL,
				slug varchar(255) NOT NULL,
				location_type varchar(50) NOT NULL,
				address text NOT NULL,
				city varchar(100) NOT NULL,
				department varchar(100) NOT NULL,
				country varchar(100) NOT NULL,
				latitude decimal(10,8) DEFAULT NULL,
				longitude decimal(11,8) DEFAULT NULL,
				phone varchar(50) DEFAULT NULL,
				email varchar(100) DEFAULT NULL,
				is_active tinyint(1) DEFAULT 1,
				is_historical tinyint(1) DEFAULT 0,
				free_pickup tinyint(1) DEFAULT 1,
				free_dropoff tinyint(1) DEFAULT 1,
				instructions text DEFAULT NULL,
				business_hours_json text DEFAULT NULL,
				sort_order int(11) DEFAULT 0,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY slug (slug)
			) $charset_collate;",

			'rrc_rate_plans' => "CREATE TABLE `{$prefix}rate_plans` (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				vehicle_model_id bigint(20) unsigned NOT NULL,
				name varchar(255) NOT NULL,
				booking_context varchar(50) NOT NULL DEFAULT 'standard',
				currency varchar(10) NOT NULL DEFAULT 'USD',
				taxes_included tinyint(1) DEFAULT 1,
				mandatory_insurance_included tinyint(1) DEFAULT 1,
				active tinyint(1) DEFAULT 1,
				effective_from datetime NOT NULL,
				effective_to datetime DEFAULT NULL,
				version int(11) DEFAULT 1,
				created_by bigint(20) unsigned DEFAULT NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id)
			) $charset_collate;",

			'rrc_rate_packages' => "CREATE TABLE `{$prefix}rate_packages` (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				rate_plan_id bigint(20) unsigned NOT NULL,
				duration_unit varchar(20) NOT NULL DEFAULT 'day',
				duration_value int(11) NOT NULL DEFAULT 1,
				normalized_days int(11) NOT NULL DEFAULT 1,
				total_amount decimal(10,2) NOT NULL,
				stackable tinyint(1) DEFAULT 1,
				priority int(11) DEFAULT 10,
				max_quantity int(11) DEFAULT NULL,
				requires_manual_quote tinyint(1) DEFAULT 0,
				guide_included tinyint(1) DEFAULT 0,
				label varchar(255) DEFAULT NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id)
			) $charset_collate;",

			'rrc_rate_adjustments' => "CREATE TABLE `{$prefix}rate_adjustments` (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				vehicle_model_id bigint(20) unsigned DEFAULT NULL,
				location_id bigint(20) unsigned DEFAULT NULL,
				name varchar(255) NOT NULL,
				adjustment_type varchar(50) NOT NULL,
				adjustment_value decimal(10,2) NOT NULL,
				date_from date NOT NULL,
				date_to date NOT NULL,
				weekdays_json text DEFAULT NULL,
				priority int(11) DEFAULT 10,
				combinable tinyint(1) DEFAULT 1,
				active tinyint(1) DEFAULT 1,
				created_at datetime NOT NULL,
				PRIMARY KEY  (id)
			) $charset_collate;",

			'rrc_quotes' => "CREATE TABLE `{$prefix}quotes` (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				public_token_hash varchar(64) NOT NULL,
				quote_number varchar(50) NOT NULL,
				customer_id bigint(20) unsigned DEFAULT NULL,
				pickup_location_id bigint(20) unsigned NOT NULL,
				return_location_id bigint(20) unsigned NOT NULL,
				pickup_at datetime NOT NULL,
				return_at datetime NOT NULL,
				chargeable_days int(11) NOT NULL,
				booking_context varchar(50) NOT NULL DEFAULT 'standard',
				currency varchar(10) NOT NULL DEFAULT 'USD',
				subtotal decimal(10,2) NOT NULL,
				tax_amount decimal(10,2) NOT NULL DEFAULT 0.00,
				insurance_amount decimal(10,2) NOT NULL DEFAULT 0.00,
				fee_amount decimal(10,2) NOT NULL DEFAULT 0.00,
				discount_amount decimal(10,2) NOT NULL DEFAULT 0.00,
				total_amount decimal(10,2) NOT NULL,
				pricing_snapshot_json text DEFAULT NULL,
				expires_at datetime NOT NULL,
				status varchar(50) NOT NULL DEFAULT 'active',
				source varchar(50) DEFAULT 'web',
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY quote_number (quote_number),
				UNIQUE KEY public_token_hash (public_token_hash)
			) $charset_collate;",

			'rrc_quote_items' => "CREATE TABLE `{$prefix}quote_items` (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				quote_id bigint(20) unsigned NOT NULL,
				vehicle_model_id bigint(20) unsigned NOT NULL,
				quantity int(11) NOT NULL DEFAULT 1,
				description text DEFAULT NULL,
				unit_amount decimal(10,2) NOT NULL,
				total_amount decimal(10,2) NOT NULL,
				pricing_breakdown_json text DEFAULT NULL,
				PRIMARY KEY  (id)
			) $charset_collate;",

			'rrc_reservations' => "CREATE TABLE `{$prefix}reservations` (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				quote_id bigint(20) unsigned DEFAULT NULL,
				public_reference varchar(50) NOT NULL,
				secure_lookup_token_hash varchar(64) NOT NULL,
				customer_id bigint(20) unsigned NOT NULL,
				vehicle_model_id bigint(20) unsigned NOT NULL,
				assigned_unit_id bigint(20) unsigned DEFAULT NULL,
				pickup_location_id bigint(20) unsigned NOT NULL,
				return_location_id bigint(20) unsigned NOT NULL,
				pickup_at datetime NOT NULL,
				return_at datetime NOT NULL,
				chargeable_days int(11) NOT NULL,
				booking_context varchar(50) NOT NULL DEFAULT 'standard',
				reservation_status varchar(50) NOT NULL DEFAULT 'draft',
				payment_status varchar(50) NOT NULL DEFAULT 'unpaid',
				operational_status varchar(50) NOT NULL DEFAULT 'unassigned',
				currency varchar(10) NOT NULL DEFAULT 'USD',
				subtotal decimal(10,2) NOT NULL,
				tax_amount decimal(10,2) NOT NULL DEFAULT 0.00,
				insurance_amount decimal(10,2) NOT NULL DEFAULT 0.00,
				fee_amount decimal(10,2) NOT NULL DEFAULT 0.00,
				discount_amount decimal(10,2) NOT NULL DEFAULT 0.00,
				total_amount decimal(10,2) NOT NULL,
				deposit_type varchar(20) DEFAULT 'percentage',
				deposit_percentage decimal(5,2) DEFAULT 10.00,
				deposit_amount decimal(10,2) NOT NULL DEFAULT 0.00,
				deposit_paid_amount decimal(10,2) NOT NULL DEFAULT 0.00,
				remaining_balance decimal(10,2) NOT NULL DEFAULT 0.00,
				remaining_balance_due_at datetime DEFAULT NULL,
				remaining_balance_status varchar(50) DEFAULT 'pending_at_pickup',
				amount_paid decimal(10,2) NOT NULL DEFAULT 0.00,
				amount_refunded decimal(10,2) NOT NULL DEFAULT 0.00,
				pricing_snapshot_json text DEFAULT NULL,
				policy_snapshot_json text DEFAULT NULL,
				customer_notes text DEFAULT NULL,
				internal_notes text DEFAULT NULL,
				source varchar(50) DEFAULT 'web',
				confirmed_at datetime DEFAULT NULL,
				checked_out_at datetime DEFAULT NULL,
				returned_at datetime DEFAULT NULL,
				cancelled_at datetime DEFAULT NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY public_reference (public_reference),
				UNIQUE KEY secure_lookup_token_hash (secure_lookup_token_hash)
			) $charset_collate;",

			'rrc_customers' => "CREATE TABLE `{$prefix}customers` (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				wp_user_id bigint(20) unsigned DEFAULT NULL,
				first_name varchar(100) NOT NULL,
				middle_name varchar(100) DEFAULT NULL,
				last_name varchar(100) NOT NULL,
				email varchar(100) NOT NULL,
				phone varchar(50) NOT NULL,
				whatsapp varchar(50) DEFAULT NULL,
				country varchar(100) NOT NULL,
				address text DEFAULT NULL,
				preferred_language varchar(10) DEFAULT 'en',
				marketing_consent tinyint(1) DEFAULT 0,
				privacy_consent_at datetime DEFAULT NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				anonymized_at datetime DEFAULT NULL,
				PRIMARY KEY  (id)
			) $charset_collate;",

			'rrc_drivers' => "CREATE TABLE `{$prefix}drivers` (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				customer_id bigint(20) unsigned NOT NULL,
				reservation_id bigint(20) unsigned DEFAULT NULL,
				driver_type varchar(50) DEFAULT 'primary',
				full_name varchar(255) NOT NULL,
				birth_date date DEFAULT NULL,
				nationality varchar(100) DEFAULT NULL,
				license_country varchar(100) DEFAULT NULL,
				license_number_encrypted text NOT NULL,
				license_expiry date DEFAULT NULL,
				passport_number_encrypted text DEFAULT NULL,
				passport_expiry date DEFAULT NULL,
				identification_type varchar(100) DEFAULT NULL,
				identification_number_encrypted text DEFAULT NULL,
				verification_status varchar(50) DEFAULT 'pending',
				verified_by bigint(20) unsigned DEFAULT NULL,
				verified_at datetime DEFAULT NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id)
			) $charset_collate;",

			'rrc_documents' => "CREATE TABLE `{$prefix}documents` (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				customer_id bigint(20) unsigned NOT NULL,
				driver_id bigint(20) unsigned DEFAULT NULL,
				reservation_id bigint(20) unsigned DEFAULT NULL,
				document_type varchar(50) NOT NULL,
				storage_key varchar(255) NOT NULL,
				original_filename varchar(255) NOT NULL,
				mime_type varchar(100) NOT NULL,
				size_bytes bigint(20) NOT NULL,
				sha256 varchar(64) NOT NULL,
				encryption_status tinyint(1) DEFAULT 0,
				malware_scan_status varchar(50) DEFAULT 'unchecked',
				verification_status varchar(50) DEFAULT 'pending',
				ai_readability_score float DEFAULT NULL,
				ai_analysis_json text DEFAULT NULL,
				expires_at date DEFAULT NULL,
				uploaded_by bigint(20) unsigned DEFAULT NULL,
				created_at datetime NOT NULL,
				deleted_at datetime DEFAULT NULL,
				PRIMARY KEY  (id)
			) $charset_collate;",

			'rrc_unit_day_locks' => "CREATE TABLE `{$prefix}unit_day_locks` (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				vehicle_unit_id bigint(20) unsigned NOT NULL,
				service_date date NOT NULL,
				reservation_id bigint(20) unsigned DEFAULT NULL,
				quote_id bigint(20) unsigned DEFAULT NULL,
				lock_type varchar(50) NOT NULL,
				status varchar(50) DEFAULT 'active',
				expires_at datetime DEFAULT NULL,
				created_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY unique_unit_date (vehicle_unit_id, service_date)
			) $charset_collate;",

			'rrc_availability_blocks' => "CREATE TABLE `{$prefix}availability_blocks` (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				vehicle_unit_id bigint(20) unsigned DEFAULT NULL,
				vehicle_model_id bigint(20) unsigned DEFAULT NULL,
				location_id bigint(20) unsigned DEFAULT NULL,
				starts_at datetime NOT NULL,
				ends_at datetime NOT NULL,
				reason text DEFAULT NULL,
				block_type varchar(50) DEFAULT 'maintenance',
				notes text DEFAULT NULL,
				created_by bigint(20) unsigned DEFAULT NULL,
				created_at datetime NOT NULL,
				PRIMARY KEY  (id)
			) $charset_collate;",

			'rrc_payments' => "CREATE TABLE `{$prefix}payments` (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				reservation_id bigint(20) unsigned NOT NULL,
				provider varchar(50) NOT NULL,
				environment varchar(20) NOT NULL DEFAULT 'sandbox',
				provider_order_id varchar(100) DEFAULT NULL,
				provider_capture_id varchar(100) DEFAULT NULL,
				provider_transaction_id varchar(100) DEFAULT NULL,
				idempotency_key varchar(100) DEFAULT NULL,
				payment_purpose varchar(50) NOT NULL DEFAULT 'security_deposit',
				currency varchar(10) NOT NULL DEFAULT 'USD',
				amount decimal(10,2) NOT NULL,
				expected_amount decimal(10,2) DEFAULT NULL,
				status varchar(50) NOT NULL DEFAULT 'pending',
				request_snapshot_json text DEFAULT NULL,
				response_snapshot_json text DEFAULT NULL,
				paid_at datetime DEFAULT NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY idempotency_key (idempotency_key)
			) $charset_collate;",

			'rrc_refunds' => "CREATE TABLE `{$prefix}refunds` (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				payment_id bigint(20) unsigned NOT NULL,
				reservation_id bigint(20) unsigned NOT NULL,
				provider_refund_id varchar(100) DEFAULT NULL,
				amount decimal(10,2) NOT NULL,
				currency varchar(10) NOT NULL DEFAULT 'USD',
				reason text DEFAULT NULL,
				policy_result_json text DEFAULT NULL,
				status varchar(50) NOT NULL DEFAULT 'pending',
				requested_by bigint(20) unsigned DEFAULT NULL,
				approved_by bigint(20) unsigned DEFAULT NULL,
				processed_at datetime DEFAULT NULL,
				created_at datetime NOT NULL,
				PRIMARY KEY  (id)
			) $charset_collate;",

			'rrc_webhook_events' => "CREATE TABLE `{$prefix}webhook_events` (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				provider varchar(50) NOT NULL,
				external_event_id varchar(100) NOT NULL,
				event_type varchar(100) NOT NULL,
				signature_verified tinyint(1) DEFAULT 0,
				payload_hash varchar(64) NOT NULL,
				payload_json text DEFAULT NULL,
				processing_status varchar(50) NOT NULL DEFAULT 'pending',
				processed_at datetime DEFAULT NULL,
				error_message text DEFAULT NULL,
				created_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY unique_event (provider, external_event_id)
			) $charset_collate;",

			'rrc_notifications' => "CREATE TABLE `{$prefix}notifications` (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				reservation_id bigint(20) unsigned DEFAULT NULL,
				customer_id bigint(20) unsigned DEFAULT NULL,
				notification_type varchar(100) NOT NULL,
				channel varchar(50) NOT NULL DEFAULT 'email',
				recipient varchar(255) NOT NULL,
				template_key varchar(100) NOT NULL,
				payload_json text DEFAULT NULL,
				status varchar(50) NOT NULL DEFAULT 'pending',
				attempts int(11) DEFAULT 0,
				last_error text DEFAULT NULL,
				sent_at datetime DEFAULT NULL,
				created_at datetime NOT NULL,
				PRIMARY KEY  (id)
			) $charset_collate;",

			'rrc_audit_log' => "CREATE TABLE `{$prefix}audit_log` (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				actor_user_id bigint(20) unsigned DEFAULT NULL,
				actor_type varchar(50) NOT NULL DEFAULT 'user',
				action varchar(255) NOT NULL,
				entity_type varchar(100) NOT NULL,
				entity_id bigint(20) unsigned NOT NULL,
				old_values_json text DEFAULT NULL,
				new_values_json text DEFAULT NULL,
				ip_hash varchar(64) DEFAULT NULL,
				user_agent_hash varchar(64) DEFAULT NULL,
				correlation_id varchar(64) DEFAULT NULL,
				created_at datetime NOT NULL,
				PRIMARY KEY  (id)
			) $charset_collate;",

			'rrc_ai_jobs' => "CREATE TABLE `{$prefix}ai_jobs` (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				job_type varchar(100) NOT NULL,
				entity_type varchar(100) NOT NULL,
				entity_id bigint(20) unsigned NOT NULL,
				provider varchar(50) DEFAULT NULL,
				model_identifier varchar(100) DEFAULT NULL,
				input_hash varchar(64) NOT NULL,
				sanitized_input_json text DEFAULT NULL,
				output_json text DEFAULT NULL,
				confidence float DEFAULT NULL,
				status varchar(50) NOT NULL DEFAULT 'pending',
				reviewed_by bigint(20) unsigned DEFAULT NULL,
				reviewed_at datetime DEFAULT NULL,
				created_at datetime NOT NULL,
				completed_at datetime DEFAULT NULL,
				PRIMARY KEY  (id)
			) $charset_collate;",
 
			'rrc_ai_usage' => "CREATE TABLE `{$prefix}ai_usage` (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				provider varchar(50) NOT NULL,
				model varchar(100) NOT NULL,
				agent_key varchar(100) NOT NULL,
				input_tokens int(11) DEFAULT 0,
				output_tokens int(11) DEFAULT 0,
				cached_tokens int(11) DEFAULT 0,
				estimated_cost decimal(10,5) DEFAULT 0.00000,
				latency_ms int(11) DEFAULT 0,
				created_at datetime NOT NULL,
				PRIMARY KEY  (id)
			) $charset_collate;",

			'rrc_ai_cache' => "CREATE TABLE `{$prefix}ai_cache` (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				cache_key varchar(100) NOT NULL,
				cache_type varchar(50) NOT NULL,
				input_hash varchar(64) NOT NULL,
				agent_key varchar(100) NOT NULL,
				prompt_version varchar(50) NOT NULL,
				normalized_query text NOT NULL,
				response_json text NOT NULL,
				confidence float DEFAULT 1.0,
				hit_count int(11) DEFAULT 0,
				expires_at datetime NOT NULL,
				created_at datetime NOT NULL,
				last_used_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY input_hash (input_hash)
			) $charset_collate;",

			'rrc_ai_memories' => "CREATE TABLE `{$prefix}ai_memories` (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				memory_scope varchar(50) NOT NULL,
				scope_id bigint(20) unsigned NOT NULL,
				memory_key varchar(100) NOT NULL,
				value_json text NOT NULL,
				sensitivity varchar(50) DEFAULT 'medium',
				expires_at datetime DEFAULT NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY unique_scope_key (memory_scope, scope_id, memory_key)
			) $charset_collate;",

			'rrc_ai_learned_rules' => "CREATE TABLE `{$prefix}ai_learned_rules` (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				agent_key varchar(100) NOT NULL,
				name varchar(255) NOT NULL,
				condition_json text NOT NULL,
				action_json text NOT NULL,
				confidence float DEFAULT 1.0,
				status varchar(50) DEFAULT 'suggested',
				created_at datetime NOT NULL,
				PRIMARY KEY  (id)
			) $charset_collate;",

			'rrc_ai_knowledge' => "CREATE TABLE `{$prefix}ai_knowledge` (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				knowledge_type varchar(100) NOT NULL,
				title varchar(255) NOT NULL,
				language varchar(10) NOT NULL DEFAULT 'es',
				content text NOT NULL,
				normalized_content text NOT NULL,
				keywords_json text DEFAULT NULL,
				version int(11) DEFAULT 1,
				approval_status varchar(50) DEFAULT 'approved',
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id)
			) $charset_collate;",

			'rrc_app_sessions' => "CREATE TABLE `{$prefix}app_sessions` (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				user_id bigint(20) unsigned NOT NULL,
				token_hash varchar(64) NOT NULL,
				ip_address varchar(45) DEFAULT NULL,
				user_agent text DEFAULT NULL,
				expires_at datetime NOT NULL,
				created_at datetime NOT NULL,
				last_activity_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY token_hash (token_hash)
			) $charset_collate;"
		];
	}

	public static function install() {
		require_once ABSPATH . 'wp-admin/includes/upgrade.php';
		$tables = self::get_tables();
		foreach ( $tables as $table_name => $sql ) {
			dbDelta( $sql );
		}
	}
}
